name: 'Get next version number'
description: 'Gets the next version number.'
inputs:
  release-type:
    description: 'The Semver release type.'
    required: true
    default: 'minor'
outputs:
  version:
    description: 'The next version number.'
    value: ${{ steps.bump-semver.outputs.new_version }}
runs:
  using: "composite"
  steps:
    - name: Get latest version from changelog
      id: changelog
      uses: mindsers/changelog-reader-action@v2
      with:
        path: ./CHANGELOG.md
    - name: Get Semver version number
      uses: actions-ecosystem/action-bump-semver@v1
      id: bump-semver
      with:
        current_version: ${{ steps.changelog.outputs.version }}
        level: ${{ inputs.release-type }}