name: Draft release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'CHANGELOG.md'
          default_author: github_actor
          fetch: false
          message: 'Prepare release ${{ github.event.inputs.version }}'
          new_branch: 'release/${{ github.event.inputs.version }}'
          push: true
      - name: Create pull request for release
        uses: thomaseizinger/create-pull-request@1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: main
          title: Release v${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Merging this PR will publish the release.
