name: Draft release
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
      version-number:
        description: 'Version number'
        required: false
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITFLOW_PUSH_TOKEN }}
      - name: Get next version number
        id: version
        uses: ./actions/get-next-version-number
        with:
          release-type: ${{ github.event.inputs.release-type }}
          version-number: ${{ github.event.inputs.version-number }}
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          version: ${{ version.outputs.version }}
          tag: v${{ version.outputs.version }}
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '["CHANGELOG.md"]'
          default_author: github_actor
          message: 'Prepare release ${{ version.outputs.version }}'
          new_branch: 'release/${{ version.outputs.version }}'
          push: true
      - name: Create pull request for release
        uses: thomaseizinger/create-pull-request@1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITFLOW_PUSH_TOKEN }}
        with:
          head: release/${{ version.outputs.version }}
          base: main
          title: Release v${{ version.outputs.version }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Merging this PR will publish the release.