name: Draft release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}
      - name: Retrieve next version number
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ github.event.inputs.version }}
          level: patch
      - name: Update version number
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'build.gradle'
          find: ${{ github.event.inputs.version }}
          replace: ${{ steps.bump-semver.outputs.new_version }}
          regex: false
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '["CHANGELOG.md", "build.gradle"]'
          default_author: github_actions
          message: 'Prepare release ${{ github.event.inputs.version }}'
          new_branch: 'release/${{ github.event.inputs.version }}'
          push: true
      - name: Create pull request for release
        uses: thomaseizinger/create-pull-request@1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: main
          title: Release v${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Merging this PR will publish the release.