name: Draft release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}
      - name: Initialize mandatory Git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}
      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit --message "Prepare release v${{ github.event.inputs.version }}"
      - name: Push release branch
        run: git push origin release/${{ github.event.inputs.version }}
      - name: Create pull request for release
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: main
          title: Release v${{ github.event.inputs.version }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Merging this PR will publish the release.
