name: Draft release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'CHANGELOG.md'
          default_author: github_actor
          message: 'Prepare release ${{ github.event.inputs.version }}'
          new_branch: 'release/${{ github.event.inputs.version }}'
          push: true
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'release/${{ github.event.inputs.version }}'
          source_branch: main
          title: Release v${{ github.event.inputs.version }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            Merging this PR will publish the release.
          reviewer: ${{ github.actor }}
          assignee: ${{ github.actor }}
          allow_no_diff: true
